services:
  postgres-auth:
    container_name: postgres-auth
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgres/data

  # auth-service:
  #   container_name: auth-service
  #   build:
  #     context: ./apps/auth-service
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres-auth
  #   env_file:
  #     - ./apps/auth-service/.env
  #   ports:
  #     - "4001:4001"
  #   command: sh -c "pnpx prisma migrate dev --name init && pnpm dev"

volumes:
  postgres_auth_data:
